all : debug release

debug : circular_buffer_debug.out

release : circular_buffer_release.out


circular_buffer_debug.out: circular_buffer.c ....
...............................
.................
gcc -ansi -pedantic-errors
...............
circular_buffer_debug.out




circular_buffer_release.out: circular_buffer.c ....
...............................
.................
gcc -ansi -pedantic-errors
...............
circular_buffer_release.out

 



