if (self.CavalryLogger) { CavalryLogger.start_js(["\/8lvi"]); }

__d("BUIAdoptionUtils",["invariant"],(function(a,b,c,d,e,f,g){"use strict";function a(a){switch(a){case"small":case"medium":return"small";case"large":return"medium";case"xlarge":case"xxlarge":return"large";case void 0:return void 0;default:g(0,3370,a)}}function b(a){switch(a){case"success":return"success";case"notify":return"information";case"recommend":return"warning";case"warn":return"error";case"quiet":return"information";case void 0:return void 0;default:g(0,3371,a)}}function c(a){return function(b){return a({value:b})}}e.exports={convertSelectorXUIOnChangeToSUIOnChange:c,convertSizeToFDSSize:a,convertUseToType:b}}),null);
__d("GroupsDispatcher",["ExplicitRegistrationDispatcher"],(function(a,b,c,d,e,f){"use strict";a=function(a){babelHelpers.inheritsLoose(b,a);function b(){return a.apply(this,arguments)||this}return b}(b("ExplicitRegistrationDispatcher"));e.exports=new a({strict:!0})}),null);
__d("PixelNumConverter",[],(function(a,b,c,d,e,f){function g(a){return a!=null&&!isNaN(a)&&isFinite(a)&&a!==""}a={pixelValue:function(a){return g(a)?Number(a)+"px":"auto"},numValue:function(a){a=a.replace("px","");return g(a)?Number(a):0}};e.exports=a}),null);
__d("stopIframe",[],(function(a,b,c,d,e,f){"use strict";function a(a){a=a.contentWindow;a.stop?a.stop():a.document.execCommand&&a.document.execCommand("Stop")}e.exports=a}),null);
__d("AdPreviewIFramePOSTRequest",["Arbiter","CSS","DOM","DOMEventListener","FBLogger","Form","lowerFacebookDomain","stopIframe"],(function(a,b,c,d,e,f){function g(a,c){if(!c)return;var d=b("DOMEventListener").add(a,"load",function(){if(!c)return;b("CSS").hide(c);d.remove();b("Arbiter").inform("AdPreview/IFrameLoadSuccess",{iframe:a})});b("CSS").show(c)}a={init:function(a,c,d,e,f){function h(){g(e,f),b("Form").post(a,c,d)}try{b("lowerFacebookDomain")()}catch(a){b("FBLogger")("ads_previews").catching(a).warn("Exception lowering domain")}h();return b("Arbiter").subscribe("contextualLayer/toggle",function(a,c){if(!b("DOM").contains(c.contentRoot,e))return;c.show?h():b("stopIframe")(e)})}};e.exports=a}),null);
__d("AdPreviewIFrameResizeListener",["Arbiter","DOM","PixelNumConverter","Style","lowerFacebookDomain"],(function(a,b,c,d,e,f){a={listen:function(a,c,d,e){var f=!1,g=!1;try{b("lowerFacebookDomain")()}catch(a){g=!0}var h=function(g){var h=g.frame,i=g.frameHeight;g=g.storyHeight;if(f||h!==a)return;c.height=i;if(!d)return;h=!e||!g?i:g-1;b("Style").set(d,"height",b("PixelNumConverter").pixelValue(h))};g&&window.addEventListener("message",function(a){a.data.event==="fb:preview:iframe/resize"&&h(a.data.data)},!1);return b("Arbiter").subscribe(["iframe/resize","contextualLayer/toggle"],function(a,d){if(a==="iframe/resize")h(d);else{if(!b("DOM").contains(d.contentRoot,c))return;d.show?f=!1:f=!0}})}};e.exports=a}),null);
__d("MenuTogglingItem",["DOM","MenuItem"],(function(a,b,c,d,e,f){a=function(a){"use strict";babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.handleClick=function(){this.toggleMenuItem();return a.prototype.handleClick.call(this)};d.toggleMenuItem=function(){this._data=babelHelpers["extends"]({},this._data,{ajaxify:this._data.toggleAjaxify,toggleAjaxify:this._data.ajaxify,value:this._data.toggleValue,toggleValue:this._data.value,markup:this._data.toggleMarkup,toggleMarkup:this._data.markup}),this._rerender()};d.setValue=function(a){this._data=babelHelpers["extends"]({},this._data,{value:a})};d._rerender=function(){var a=this._anchor;b("DOM").replace(a,this._renderItemContent())};return c}(b("MenuItem"));e.exports=a}),null);
__d("getEventTarget",[],(function(a,b,c,d,e,f){"use strict";var g=3;function a(a){a=a.target||a.srcElement||window;a.correspondingUseElement&&(a=a.correspondingUseElement);return a.nodeType===g?a.parentNode:a}e.exports=a}),null);
__d("XCookiesPolicyController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/policies/cookies/",{ref:{type:"String"},locale:{type:"String"},settings_tracking:{type:"String"},list:{type:"Exists",defaultValue:!1}})}),null);
__d("XPagesTransparencyDialogController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/pages/transparency/transparency_dialog/",{hide_ads_summary:{type:"Bool",defaultValue:!1},page_id:{type:"FBID",required:!0},active_tab:{type:"Enum",enumType:1},__asyncDialog:{type:"Int"}})}),null);